import { CustomizerItem, ColorSwatch, CharacterPreset, CharacterState } from '@/types/customizer';

export const COLOR_SWATCHES: ColorSwatch[] = [
  { id: 'gold', name: 'Royal Gold', hex: '#F59E0B' },
  { id: 'cyan', name: 'Cyber Cyan', hex: '#06B6D4' },
  { id: 'crimson', name: 'Crimson Red', hex: '#EF4444' },
  { id: 'emerald', name: 'Emerald Green', hex: '#10B981' },
  { id: 'purple', name: 'Neon Violet', hex: '#8B5CF6' },
  { id: 'rose', name: 'Blush Pink', hex: '#EC4899' },
  { id: 'silver', name: 'Titanium Silver', hex: '#94A3B8' },
  { id: 'obsidian', name: 'Obsidian Black', hex: '#1E293B', border: '#475569' },
];

export const CATEGORIES = [
  { id: 'wardrobe', name: 'Wardrobe', icon: 'Shirt', count: 6 },
  { id: 'characters', name: 'Characters', icon: 'User', count: 3 },
  { id: 'backgrounds', name: 'Backdrop', icon: 'Image', count: 6 },
  { id: 'accessories', name: 'Accessories', icon: 'Glasses', count: 6 },
  { id: 'lighting', name: 'Mood & Lighting', icon: 'Sparkles', count: 5 },
] as const;

export const CUSTOMIZER_ITEMS: CustomizerItem[] = [
  // Characters
  {
    id: 'char-bruce',
    name: 'Bruce Wayne',
    category: 'characters',
    subCategory: 'Formal',
    thumbnail: '/Bruce Wayne Christian Bale.jpg',
    image: '/Bruce Wayne Christian Bale.jpg',
    tag: 'Billionaire',
    description: 'Bespoke charisma, poised and aristocratic demeanor.',
  },
  {
    id: 'char-knight',
    name: 'The Dark Knight',
    category: 'characters',
    subCategory: 'Tactical',
    thumbnail: '/The Dark Knight Why Do We Fall.jpg',
    image: '/The Dark Knight Why Do We Fall.jpg',
    tag: 'Vigilante',
    description: 'Armored combatant ready to defend the nocturnal skyline.',
  },
  {
    id: 'char-dancer',
    name: 'Urban Dancer',
    category: 'characters',
    subCategory: 'Streetwear',
    thumbnail: '/Step Up Movies.jpg',
    image: '/Step Up Movies.jpg',
    tag: 'Athletic',
    description: 'High energy, street-ready hip-hop fashion and posture.',
  },

  // Wardrobe / Outfits
  {
    id: 'wardrobe-tux',
    name: 'Bespoke Peak-Lapel Tux',
    category: 'wardrobe',
    subCategory: 'Formal',
    thumbnail: '/Bruce Wayne Christian Bale.jpg',
    accentColor: '#1e293b',
    tag: 'Luxury',
    description: 'Hand-tailored wool with satin lapels for black-tie galas.',
  },
  {
    id: 'wardrobe-batsuit',
    name: 'Tactical Kevlar Batsuit',
    category: 'wardrobe',
    subCategory: 'Tactical',
    thumbnail: '/The Dark Knight Why Do We Fall.jpg',
    accentColor: '#0f172a',
    tag: 'Combat',
    description: 'Titanium-weave ballistic plating with reinforced cowl.',
  },
  {
    id: 'wardrobe-street',
    name: 'Oversized Urban Hoodie',
    category: 'wardrobe',
    subCategory: 'Streetwear',
    thumbnail: '/Step Up Movies.jpg',
    accentColor: '#475569',
    tag: 'Casual',
    description: 'Heavyweight loopback cotton hoodie with utility jogger.',
  },
  {
    id: 'wardrobe-cyber-jacket',
    name: 'Neon Techwear Shell',
    category: 'wardrobe',
    subCategory: 'Streetwear',
    thumbnail: '/4K Dark Wallpaper For Pc Gallery.jpg',
    accentColor: '#06b6d4',
    tag: 'Futuristic',
    description: 'Waterproof nylon shell featuring luminous reflective piping.',
  },
  {
    id: 'wardrobe-leather',
    name: 'Biker Stealth Leather',
    category: 'wardrobe',
    subCategory: 'Casual',
    thumbnail: '/Bruce Wayne Christian Bale.jpg',
    accentColor: '#334155',
    tag: 'Rebel',
    description: 'Distressed asymmetric zip moto jacket with quilted shoulders.',
  },
  {
    id: 'wardrobe-gold-tux',
    name: 'Gilded Velvet Blazer',
    category: 'wardrobe',
    subCategory: 'Formal',
    thumbnail: '/Bruce Wayne Christian Bale.jpg',
    accentColor: '#d97706',
    tag: 'VIP Edition',
    description: 'Deep midnight velvet with 24k gold embroidered trims.',
  },

  // Backgrounds
  {
    id: 'bg-sunset',
    name: 'Sunset Pastel Horizon',
    category: 'backgrounds',
    subCategory: 'Aesthetic',
    thumbnail: '/1920x1080 Macbook Wallpaper Aesthetic.jpg',
    image: '/1920x1080 Macbook Wallpaper Aesthetic.jpg',
    tag: 'Calm',
    description: 'Warm dreamlike gradient dusk over a calm minimalist coastline.',
  },
  {
    id: 'bg-dark-alley',
    name: 'Neon Cyber Rain Alley',
    category: 'backgrounds',
    subCategory: 'Dark/Cyber',
    thumbnail: '/4K Dark Wallpaper For Pc Gallery.jpg',
    image: '/4K Dark Wallpaper For Pc Gallery.jpg',
    tag: 'Nocturnal',
    description: 'High-contrast wet asphalt illuminated by neon city billboards.',
  },
  {
    id: 'bg-alpine',
    name: 'Alpine Horizon 8K',
    category: 'backgrounds',
    subCategory: 'Nature',
    thumbnail: '/Desktop Wallpapers 8k.jpg',
    image: '/Desktop Wallpapers 8k.jpg',
    tag: 'Crisp',
    description: 'Majestic mountain peaks beneath an azure clear sky.',
  },
  {
    id: 'bg-grid',
    name: 'Obsidian Digital Matrix',
    category: 'backgrounds',
    subCategory: 'Tech',
    thumbnail: '/Wallpaper Pc 4k 1920x1080.jpg',
    image: '/Wallpaper Pc 4k 1920x1080.jpg',
    tag: 'Minimal',
    description: 'Geometric monochrome perspective grid with subtle neon refraction.',
  },
  {
    id: 'bg-studio-dark',
    name: 'Executive Studio Spotlight',
    category: 'backgrounds',
    subCategory: 'Studio',
    thumbnail: '/Bruce Wayne Christian Bale.jpg',
    tag: 'Studio',
    description: 'Deep slate studio cyclorama with overhead circular softbox light.',
  },
  {
    id: 'bg-tokyo-drift',
    name: 'Underground Street Rave',
    category: 'backgrounds',
    subCategory: 'Dark/Cyber',
    thumbnail: '/Step Up Movies.jpg',
    tag: 'Urban',
    description: 'Subterranean concrete garage pulsing with amber strobe lights.',
  },

  // Accessories
  {
    id: 'acc-none',
    name: 'None (Clean Look)',
    category: 'accessories',
    subCategory: 'Minimal',
    thumbnail: '',
    tag: 'Default',
    description: 'No extra accessories.',
  },
  {
    id: 'acc-shades',
    name: 'Midnight Aviator Shades',
    category: 'accessories',
    subCategory: 'Eyewear',
    thumbnail: '',
    tag: 'Iconic',
    description: 'Blacked-out polarized lenses with matte titanium wire frames.',
  },
  {
    id: 'acc-cyber-hud',
    name: 'Holo-Lens Cyber Visor',
    category: 'accessories',
    subCategory: 'Futuristic',
    thumbnail: '',
    tag: 'Cyber',
    description: 'Transparent cyan holographic HUD projecting biometric telemetry.',
  },
  {
    id: 'acc-gold-chain',
    name: 'Diamond Cuban Link',
    category: 'accessories',
    subCategory: 'Jewelry',
    thumbnail: '',
    tag: 'Prestige',
    description: 'Heavy 18k solid gold chain with pavé diamond clasp.',
  },
  {
    id: 'acc-tactical-comms',
    name: 'Covert Earpiece Comms',
    category: 'accessories',
    subCategory: 'Gear',
    thumbnail: '',
    tag: 'Tactical',
    description: 'Encrypted tactical radio earpiece with boom microphone.',
  },
  {
    id: 'acc-stealth-mask',
    name: 'Obsidian Half-Mask',
    category: 'accessories',
    subCategory: 'Gear',
    thumbnail: '',
    tag: 'Covert',
    description: 'Breathable carbon-fiber face shield with air filtration valves.',
  },

  // Mood & Lighting
  {
    id: 'light-cinematic',
    name: 'Gotham Noir (Dramatic)',
    category: 'lighting',
    subCategory: 'Dramatic',
    thumbnail: '',
    accentColor: '#3b82f6',
    tag: 'Cinematic',
    description: 'Low-key rim lighting with cool blue shadows and sharp highlights.',
  },
  {
    id: 'light-cyberpunk',
    name: 'Cyberpunk Neon (Magenta/Cyan)',
    category: 'lighting',
    subCategory: 'Neon',
    thumbnail: '',
    accentColor: '#ec4899',
    tag: 'Vibrant',
    description: 'Dual-tone split lighting: hot pink left, electric cyan right.',
  },
  {
    id: 'light-golden',
    name: 'Sunset Golden Hour',
    category: 'lighting',
    subCategory: 'Warm',
    thumbnail: '',
    accentColor: '#f59e0b',
    tag: 'Golden',
    description: 'Radiant amber flare wrapping the character in golden warmth.',
  },
  {
    id: 'light-clean',
    name: 'Commercial Studio Softbox',
    category: 'lighting',
    subCategory: 'Studio',
    thumbnail: '',
    accentColor: '#ffffff',
    tag: 'Neutral',
    description: 'Even, balanced diffused white lighting for pure fashion clarity.',
  },
  {
    id: 'light-matrix',
    name: 'Matrix Acid Green',
    category: 'lighting',
    subCategory: 'Neon',
    thumbnail: '',
    accentColor: '#10b981',
    tag: 'Sci-Fi',
    description: 'Subtle radioactive green back-glow with glitch digital aura.',
  },
];

export const INITIAL_CHARACTER_STATE: CharacterState = {
  characterId: 'char-bruce',
  wardrobeId: 'wardrobe-tux',
  backgroundId: 'bg-sunset',
  accessoryId: 'acc-none',
  lightingId: 'light-cinematic',
  primaryColor: '#F59E0B',
  zoomMode: 'fit',
  showVignette: true,
  backgroundBlur: 0,
  ambientGlow: true,
  expression: 'confident',
};

export const PRESETS: CharacterPreset[] = [
  {
    id: 'preset-bruce',
    name: 'The Gotham Tycoon',
    subtitle: 'Bespoke Black-Tie & Penthouse Dusk',
    previewImage: '/Bruce Wayne Christian Bale.jpg',
    state: {
      characterId: 'char-bruce',
      wardrobeId: 'wardrobe-tux',
      backgroundId: 'bg-sunset',
      accessoryId: 'acc-none',
      lightingId: 'light-golden',
      primaryColor: '#F59E0B',
      zoomMode: 'bust',
      showVignette: true,
      backgroundBlur: 0,
      ambientGlow: true,
      expression: 'confident',
    },
  },
  {
    id: 'preset-batman',
    name: 'The Dark Vigilante',
    subtitle: 'Tactical Kevlar & Rain-Soaked Streets',
    previewImage: '/The Dark Knight Why Do We Fall.jpg',
    state: {
      characterId: 'char-knight',
      wardrobeId: 'wardrobe-batsuit',
      backgroundId: 'bg-dark-alley',
      accessoryId: 'acc-tactical-comms',
      lightingId: 'light-cinematic',
      primaryColor: '#06B6D4',
      zoomMode: 'fit',
      showVignette: true,
      backgroundBlur: 2,
      ambientGlow: true,
      expression: 'fierce',
    },
  },
  {
    id: 'preset-street',
    name: 'Apex Street Dancer',
    subtitle: 'Heavyweight Fleece & Alpine Edge',
    previewImage: '/Step Up Movies.jpg',
    state: {
      characterId: 'char-dancer',
      wardrobeId: 'wardrobe-street',
      backgroundId: 'bg-alpine',
      accessoryId: 'acc-gold-chain',
      lightingId: 'light-cyberpunk',
      primaryColor: '#EC4899',
      zoomMode: 'bust',
      showVignette: false,
      backgroundBlur: 0,
      ambientGlow: true,
      expression: 'chill',
    },
  },
  {
    id: 'preset-cyber',
    name: 'Neo Matrix Operative',
    subtitle: 'Techwear Shell & Digital Void',
    previewImage: '/4K Dark Wallpaper For Pc Gallery.jpg',
    state: {
      characterId: 'char-knight',
      wardrobeId: 'wardrobe-cyber-jacket',
      backgroundId: 'bg-grid',
      accessoryId: 'acc-cyber-hud',
      lightingId: 'light-matrix',
      primaryColor: '#10B981',
      zoomMode: 'fit',
      showVignette: true,
      backgroundBlur: 0,
      ambientGlow: true,
      expression: 'confident',
    },
  },
];
